"""init

Revision ID: af5fdb4a3416
Revises: f70a130f5a5a
Create Date: 2024-05-30 11:41:54.413166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5fdb4a3416'
down_revision = 'f70a130f5a5a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
